const MS_PER_HOUR = 60 * 60 * 1000;

const SIGNING_REMINDER_AFTER_HOURS = 6;
const SIGNING_URGENT_BEFORE_HOURS = 1;
const FIRST_RENT_REMINDER_DAYS_BEFORE_DUE = 1;
const CHECK_IN_EXPIRY_DAYS = 3;
const CONTRACT_EXPIRING_SOON_THRESHOLD_DAYS = 30;

module.exports = {
  MS_PER_HOUR,
  SIGNING_REMINDER_AFTER_HOURS,
  SIGNING_URGENT_BEFORE_HOURS,
  FIRST_RENT_REMINDER_DAYS_BEFORE_DUE,
  CHECK_IN_EXPIRY_DAYS,
  CONTRACT_EXPIRING_SOON_THRESHOLD_DAYS,
};
