// constants/roles.js
const ROLES = {
  ADMIN: 'ADMIN',
  BUILDING_MANAGER: 'BUILDING_MANAGER',
  STAFF: 'STAFF',
  RESIDENT: 'RESIDENT',
  CUSTOMER: 'CUSTOMER',
};

const ADMIN_MANAGEABLE_ROLES = [
  ROLES.BUILDING_MANAGER,
  ROLES.STAFF,
];

module.exports = { ROLES, ADMIN_MANAGEABLE_ROLES };